### ISSUE TITLE
Upgrade Galleon version to 5.2.0.Final

### ISSUE THREAD

**Issue by yersan** [wildfly-extras/prospero#467]
I've tried to build a WildFly SNAPSHOT version with Prospero but I get the following error. It looks like Propspero is not prepared to handle the `urn:jboss:galleon:layer-spec:2.0` yet. 

It seems that upgrading Galleon to 5.2.0.Final is required to use it with the latest WidlFly version.

```
prospero (1.1.x) $ rm -rf /tmp/wildfly-prospero && \                                                                       1 ↵
 ./dist/build/target/prospero-1.1.1.Final-SNAPSHOT/bin/prospero.sh install \
 --dir=/tmp/wildfly-prospero \
 --definition=/tmp/provisioning.xml \
 --channel=/tmp/wildfly-channels.yaml --verbose
```

```
installing galleon provisioning definition: /tmp/provisioning.xml
Using channels:
# manifest: org.wildfly:wildfly-ee-galleon-pack:30.0.0.Beta1-SNAPSHOT
  repositories:
    id: central
    url: https://repo1.maven.org/maven2/
    id: jboss-public
    url: https://repository.jboss.org/nexus/content/groups/public/
# manifest: org.wildfly.prospero:prospero-wildfly-galleon-pack:1.1.1.Final-SNAPSHOT
  repositories:
    id: central
    url: https://repo1.maven.org/maven2/
    id: jboss-public
    url: https://repository.jboss.org/nexus/content/groups/public/

Feature-packs resolved.


Failed to parse provisioning configuration: /layers/standalone/undertow-load-balancer/layer-spec.xml

org.jboss.galleon.ProvisioningException: Failed to parse /layers/standalone/undertow-load-balancer/layer-spec.xml
	at org.jboss.prospero//org.jboss.galleon.xml.XmlParsers.parseConfigLayerSpec(XmlParsers.java:73)
	at org.jboss.prospero//org.jboss.galleon.runtime.FeaturePackRuntimeBuilder.getConfigLayer(FeaturePackRuntimeBuilder.java:219)
	at org.jboss.prospero//org.jboss.galleon.runtime.ProvisioningRuntimeBuilder.resolveConfigLayer(ProvisioningRuntimeBuilder.java:518)
	at org.jboss.prospero//org.jboss.galleon.runtime.ProvisioningRuntimeBuilder.resolveConfigLayer(ProvisioningRuntimeBuilder.java:499)
	at org.jboss.prospero//org.jboss.galleon.runtime.ProvisioningRuntimeBuilder.includeLayer(ProvisioningRuntimeBuilder.java:471)
	at org.jboss.prospero//org.jboss.galleon.runtime.ProvisioningRuntimeBuilder.popConfig(ProvisioningRuntimeBuilder.java:461)
	at org.jboss.prospero//org.jboss.galleon.runtime.ProvisioningRuntimeBuilder.processFpConfig(ProvisioningRuntimeBuilder.java:381)
	at org.jboss.prospero//org.jboss.galleon.runtime.ProvisioningRuntimeBuilder.processFpDepConfigs(ProvisioningRuntimeBuilder.java:415)
	at org.jboss.prospero//org.jboss.galleon.runtime.ProvisioningRuntimeBuilder.doBuild(ProvisioningRuntimeBuilder.java:214)
	at org.jboss.prospero//org.jboss.galleon.runtime.ProvisioningRuntimeBuilder.build(ProvisioningRuntimeBuilder.java:157)
	at org.jboss.prospero//org.jboss.galleon.ProvisioningManager.getRuntimeInternal(ProvisioningManager.java:640)
	at org.jboss.prospero//org.jboss.galleon.ProvisioningManager.doProvision(ProvisioningManager.java:645)
	at org.jboss.prospero//org.jboss.galleon.ProvisioningManager.provision(ProvisioningManager.java:405)
	at org.jboss.prospero//org.wildfly.prospero.actions.ProvisioningAction.lambda$provision$0(ProvisioningAction.java:131)
	at org.jboss.prospero//org.wildfly.prospero.galleon.GalleonUtils.executeGalleon(GalleonUtils.java:106)
	at org.jboss.prospero//org.wildfly.prospero.actions.ProvisioningAction.provision(ProvisioningAction.java:131)
	at org.jboss.prospero//org.wildfly.prospero.cli.commands.InstallCommand.call(InstallCommand.java:187)
	at org.jboss.prospero//org.wildfly.prospero.cli.commands.InstallCommand.call(InstallCommand.java:50)
	at org.jboss.prospero//picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at org.jboss.prospero//picocli.CommandLine.access$1500(CommandLine.java:148)
	at org.jboss.prospero//picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at org.jboss.prospero//picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at org.jboss.prospero//picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at org.jboss.prospero//picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at org.jboss.prospero//picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at org.jboss.prospero//picocli.CommandLine.execute(CommandLine.java:2170)
	at org.jboss.prospero//org.wildfly.prospero.cli.CliMain.main(CliMain.java:58)
	at org.jboss.modules.Module.run(Module.java:353)
	at org.jboss.modules.Module.run(Module.java:321)
	at org.jboss.modules.Main.main(Main.java:604)
Caused by: org.jboss.galleon.ProvisioningException: Failed to parse config layer spec
	at org.jboss.prospero//org.jboss.galleon.xml.XmlParsers.parseConfigLayerSpec(XmlParsers.java:83)
	at org.jboss.prospero//org.jboss.galleon.xml.XmlParsers.parseConfigLayerSpec(XmlParsers.java:71)
	... 29 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[2,84]
Message: Unexpected element '{urn:jboss:galleon:layer-spec:2.0}layer-spec'
	at org.jboss.prospero-dep//org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:120)
	at org.jboss.prospero-dep//org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:76)
	at org.jboss.prospero//org.jboss.galleon.xml.XmlParsers.doParse(XmlParsers.java:111)
	at org.jboss.prospero//org.jboss.galleon.xml.XmlParsers.parse(XmlParsers.java:66)
	at org.jboss.prospero//org.jboss.galleon.xml.XmlParsers.parseConfigLayerSpec(XmlParsers.java:81)
	... 30 more
```

**Comment by yersan** [comment]
My fault, I have to use main branch, sorry for the noise.
