### ISSUE TITLE
Class loader issue with jboss-modules

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/prospero#73]
```
[thofman@rama prospero]$ dist/build/target/prospero-1.0-SNAPSHOT/bin/prospero.sh install --dir wf-core --provision-config wildfly-core-config.yaml --fpl "wildfly-core@maven(org.jboss.universe:community-universe):19.0"
Listening for transport dt_socket at address: 8787
Installing wildfly-core@maven(org.jboss.universe:community-universe):19.0
Feature-packs resolved.0%
Packages installed. 100%
JBoss modules installed. 100%
Generating configurationError while executing operation 'install': Failed to invoke config generator org.wildfly.galleon.plugin.config.generator.WfConfigGenerator
Jun 28, 2022 12:28:51 PM org.wildfly.prospero.cli.commands.InstallCommand call
ERROR: Error while executing operation 'install': Failed to invoke config generator org.wildfly.galleon.plugin.config.generator.WfConfigGenerator
org.jboss.galleon.ProvisioningException: Failed to invoke config generator org.wildfly.galleon.plugin.config.generator.WfConfigGenerator
	at org.wildfly.galleon.plugin.WfInstallPlugin.generateConfigs(WfInstallPlugin.java:740)
	at org.wildfly.galleon.plugin.WfInstallPlugin.postInstall(WfInstallPlugin.java:471)
	at org.jboss.prospero//org.jboss.galleon.runtime.ProvisioningRuntime$3.visitPlugin(ProvisioningRuntime.java:263)
	at org.jboss.prospero//org.jboss.galleon.runtime.ProvisioningRuntime$3.visitPlugin(ProvisioningRuntime.java:260)
	at org.jboss.prospero//org.jboss.galleon.layout.ProvisioningLayout$Handle.visitPlugins(ProvisioningLayout.java:285)
	at org.jboss.prospero//org.jboss.galleon.layout.ProvisioningLayout.visitPlugins(ProvisioningLayout.java:838)
	at org.jboss.prospero//org.jboss.galleon.runtime.ProvisioningRuntime.provision(ProvisioningRuntime.java:260)
	at org.jboss.prospero//org.jboss.galleon.ProvisioningManager.doProvision(ProvisioningManager.java:644)
	at org.jboss.prospero//org.jboss.galleon.ProvisioningManager.provision(ProvisioningManager.java:403)
	at org.jboss.prospero//org.wildfly.prospero.actions.Provision.lambda$provision$0(Provision.java:113)
	at org.jboss.prospero//org.wildfly.prospero.galleon.GalleonUtils.executeGalleon(GalleonUtils.java:51)
	at org.jboss.prospero//org.wildfly.prospero.actions.Provision.provision(Provision.java:113)
	at org.jboss.prospero//org.wildfly.prospero.cli.commands.InstallCommand.call(InstallCommand.java:128)
	at org.jboss.prospero//org.wildfly.prospero.cli.commands.InstallCommand.call(InstallCommand.java:22)
	at org.jboss.prospero//picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at org.jboss.prospero//picocli.CommandLine.access$1300(CommandLine.java:145)
	at org.jboss.prospero//picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at org.jboss.prospero//picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at org.jboss.prospero//picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at org.jboss.prospero//picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at org.jboss.prospero//picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at org.jboss.prospero//picocli.CommandLine.execute(CommandLine.java:2078)
	at org.jboss.prospero//org.wildfly.prospero.cli.CliMain.main(CliMain.java:53)
	at org.jboss.modules.Module.run(Module.java:353)
	at org.jboss.modules.Module.run(Module.java:321)
	at org.jboss.modules.Main.main(Main.java:604)
Caused by: java.lang.IllegalStateException: WFLYEMB0018: Cannot get reflective method 'create' for: org.wildfly.core.embedded.EmbeddedStandaloneServerFactory
	at org.wildfly.core.embedded.EmbeddedProcessFactory.createStandaloneServer(EmbeddedProcessFactory.java:184)
	at org.wildfly.core.embedded.EmbeddedProcessFactory.createStandaloneServer(EmbeddedProcessFactory.java:114)
	at org.wildfly.galleon.plugin.config.generator.BaseConfigGenerator.doStartServer(BaseConfigGenerator.java:212)
	at org.wildfly.galleon.plugin.config.generator.WfConfigGenerator.startServer(WfConfigGenerator.java:151)
	at org.wildfly.galleon.plugin.config.generator.WfProvisionedConfigHandler.prepare(WfProvisionedConfigHandler.java:430)
	at org.jboss.prospero//org.jboss.galleon.runtime.ResolvedConfig.handle(ResolvedConfig.java:129)
	at org.wildfly.galleon.plugin.config.generator.WfConfigGenerator.doGenerate(WfConfigGenerator.java:93)
	at org.wildfly.galleon.plugin.config.generator.WfConfigGenerator.generate(WfConfigGenerator.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.wildfly.galleon.plugin.WfInstallPlugin.generateConfigs(WfInstallPlugin.java:731)
	... 25 more
Caused by: java.lang.NoSuchMethodException: org.wildfly.core.embedded.EmbeddedStandaloneServerFactory.create(java.io.File, org.jboss.modules.ModuleLoader, java.util.Properties, java.util.Map, [Ljava.lang.String;)
	at java.base/java.lang.Class.getMethod(Class.java:2108)
	at org.wildfly.core.embedded.EmbeddedProcessFactory.createStandaloneServer(EmbeddedProcessFactory.java:182)
	... 37 more
```

I think the root cause is that when looking for the `create` method here: https://github.com/wildfly/wildfly-core/blob/main/embedded/src/main/java/org/wildfly/core/embedded/EmbeddedProcessFactory.java#L177
the `ModuleLoader` class passed as the argument of the `getMethod()` call comes from a different class loader.

**Comment by TomasHofman** [comment]
Cc @spyrkob, in case you would know what's wrong from the top of your head.

**Comment by spyrkob** [comment]
Yes, basically the `GalleonUtils#JBOSS_FORK_EMBEDDED_VALUE` needs to be set to true, but it won't correctly work with Wildfly FP until it releases new FP with galleon-plugins >= 6.0.0.Alpha2.

I'll assign that to myself - there's another fix in Galleon needed as well

**Comment by spyrkob** [comment]
related to #76 and #68
