### ISSUE TITLE
Can not install in offline mode

### ISSUE THREAD

**Issue by jmesnil** [wildfly-extras/prospero#95]
Base on a "local" remote repository, I'm able to instal EAP:

```
 ./prospero install --fpl=eap-8.0 --dir=eap8 --channel-repo=file:///Users/jmesnil/tmp/jboss-eap-8.0.0.Beta-maven-repository/maven-repository/
Installing org.jboss.eap:wildfly-ee-galleon-pack:8.0.0.Beta-redhat-20220627
Feature-packs resolved.
...
Configurations generated.
```

However if I try to do the same in offline mode it fails:

```
./prospero install --fpl=eap-8.0 --dir=eap8 --channel-repo=file:///Users/jmesnil/tmp/jboss-eap-8.0.0.Beta-maven-repository/maven-repository/ --offline --local-repo=/Users/jmesnil/.m2/repository
Error while executing operation 'install': Unable to resolve versions of org.jboss.eap.channels:eap-8.0-beta:yaml:channel:[1.0.0.Beta-redhat-00001,)
  remote repositories:
  * https://maven.repository.redhat.com/ga/
  * https://repo1.maven.org/maven2/
  * file:/Users/jmesnil/tmp/jboss-eap-8.0.0.Beta-maven-repository/maven-repository/
  local repository: /Users/jmesnil/.m2/repository
09:49:54,438 ERROR [InstallCommand] Error while executing operation 'install': Unable to resolve versions of org.jboss.eap.channels:eap-8.0-beta:yaml:channel:[1.0.0.Beta-redhat-00001,)
  remote repositories:
  * https://maven.repository.redhat.com/ga/
  * https://repo1.maven.org/maven2/
  * file:/Users/jmesnil/tmp/jboss-eap-8.0.0.Beta-maven-repository/maven-repository/
  local repository: /Users/jmesnil/.m2/repository: org.wildfly.prospero.api.exceptions.ArtifactResolutionException: Unable to resolve versions of org.jboss.eap.channels:eap-8.0-beta:yaml:channel:[1.0.0.Beta-redhat-00001,)
  remote repositories:
  * https://maven.repository.redhat.com/ga/
  * https://repo1.maven.org/maven2/
  * file:/Users/jmesnil/tmp/jboss-eap-8.0.0.Beta-maven-repository/maven-repository/
  local repository: /Users/jmesnil/.m2/repository
        at org.wildfly.prospero.wfchannel.ChannelRefUpdater.resolveChannelFile(ChannelRefUpdater.java:94)
        at org.wildfly.prospero.wfchannel.ChannelRefUpdater.resolveLatest(ChannelRefUpdater.java:50)
        at org.wildfly.prospero.wfchannel.ChannelRefUpdater.resolveLatest(ChannelRefUpdater.java:66)
        at org.wildfly.prospero.galleon.GalleonEnvironment.<init>(GalleonEnvironment.java:61)
        at org.wildfly.prospero.galleon.GalleonEnvironment$Builder.build(GalleonEnvironment.java:152)
        at org.wildfly.prospero.actions.ProvisioningAction.provision(ProvisioningAction.java:75)
        at org.wildfly.prospero.cli.commands.InstallCommand.call(InstallCommand.java:122)
        at org.wildfly.prospero.cli.commands.InstallCommand.call(InstallCommand.java:22)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.wildfly.prospero.cli.CliMain.main(CliMain.java:59)
```

**Comment by spyrkob** [comment]
`--offline` prevents maven from resolving any remote repositories - since the repository from `channel-repo` is added as a remote repository, it will prevent resolving from that as well.

Following should work correctly:
`./prospero install --fpl=eap-8.0 --dir=eap8 --offline --local-repo=/Users/jmesnil/tmp/jboss-eap-8.0.0.Beta-maven-repository/maven-repository/`
